In [1]:
from mxnet import ndarray as nd

/home/dyjng/anaconda3/lib/python3.6/site-packages/urllib3/contrib/pyopenssl.py:46: DeprecationWarning: OpenSSL.rand is deprecated - you should use os.urandom instead
  import OpenSSL.SSL


In [2]:
nd.zeros((3, 5))


[[ 0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.]]
<NDArray 3x5 @cpu(0)>

In [3]:
x = nd.ones((3, 5))
x


[[ 1.  1.  1.  1.  1.]
 [ 1.  1.  1.  1.  1.]
 [ 1.  1.  1.  1.  1.]]
<NDArray 3x5 @cpu(0)>

In [4]:
nd.array([[1, 2], [3, 4]])


[[ 1.  2.]
 [ 3.  4.]]
<NDArray 2x2 @cpu(0)>

In [5]:
y = nd.random_normal(0, 1, shape = (3, 5))

In [6]:
y.shape

(3, 5)

In [7]:
y.size

15

In [8]:
x + y


[[ 1.30030751  1.23107231  2.0493288   0.67566067  0.99021119]
 [ 1.73686242  2.72023439  1.46656418 -0.07333767  1.87809837]
 [ 0.73282301  0.1307435  -0.16747034  0.48451167  1.51638651]]
<NDArray 3x5 @cpu(0)>

In [9]:
x * y


[[ 0.30030754  0.23107235  1.04932892 -0.32433933 -0.0097888 ]
 [ 0.73686236  1.72023427  0.46656415 -1.07333767  0.87809837]
 [-0.26717702 -0.8692565  -1.16747034 -0.51548833  0.51638645]]
<NDArray 3x5 @cpu(0)>

In [10]:
nd.exp(y)


[[ 1.35027397  1.2599504   2.85573411  0.72300488  0.99025893]
 [ 2.08936954  5.58583689  1.59450626  0.34186557  2.40631938]
 [ 0.76553756  0.41926315  0.31115305  0.59720892  1.67596054]]
<NDArray 3x5 @cpu(0)>

In [11]:
nd.dot(x, y.T)


[[ 1.2465806   2.72842145 -2.3030057 ]
 [ 1.2465806   2.72842145 -2.3030057 ]
 [ 1.2465806   2.72842145 -2.3030057 ]]
<NDArray 3x3 @cpu(0)>

In [12]:
a = nd.arange(3).reshape((3, 1))
b = nd.arange(2).reshape((1, 2))
print('a:', a)
print('b:', b)
print('a+b:', a + b)

a: 
[[ 0.]
 [ 1.]
 [ 2.]]
<NDArray 3x1 @cpu(0)>
b: 
[[ 0.  1.]]
<NDArray 1x2 @cpu(0)>
a+b: 
[[ 0.  1.]
 [ 1.  2.]
 [ 2.  3.]]
<NDArray 3x2 @cpu(0)>


In [13]:
import numpy as np
x = np.ones((2, 3))
y = nd.array(x) # numpy --> mxnet
z = y.asnumpy() # mxnet --> numpy
print([z, y])

[array([[ 1.,  1.,  1.],
       [ 1.,  1.,  1.]], dtype=float32), 
[[ 1.  1.  1.]
 [ 1.  1.  1.]]
<NDArray 2x3 @cpu(0)>]


In [14]:
x = nd.ones((3, 5))
y = nd.ones((3, 5))

before = id(y)
y = x + y
id(y) == before
# print(y)

False

In [15]:
z = nd.zeros_like(x)
before = id(z)
z[:] = x + y
id(z) == before
# print(z)

True

In [16]:
nd.elemwise_add(x, y, out = z)
id(z) == before
# print(z)

True

In [17]:
before = id(x)
x += y
id(x) == before

True

In [18]:
x = nd.arange(9).reshape((3,3))
print('x:', x)
x[1:3]

x: 
[[ 0.  1.  2.]
 [ 3.  4.  5.]
 [ 6.  7.  8.]]
<NDArray 3x3 @cpu(0)>



[[ 3.  4.  5.]
 [ 6.  7.  8.]]
<NDArray 2x3 @cpu(0)>

In [19]:
x[1, 2] = 9.0
x


[[ 0.  1.  2.]
 [ 3.  4.  9.]
 [ 6.  7.  8.]]
<NDArray 3x3 @cpu(0)>

In [20]:
x = nd.arange(9).reshape((3, 3))
print('x:', x)
x[1:2, 1:3]

x: 
[[ 0.  1.  2.]
 [ 3.  4.  5.]
 [ 6.  7.  8.]]
<NDArray 3x3 @cpu(0)>



[[ 4.  5.]]
<NDArray 1x2 @cpu(0)>

In [21]:
x[1:2, 1:3] = 9.0
x


[[ 0.  1.  2.]
 [ 3.  9.  9.]
 [ 6.  7.  8.]]
<NDArray 3x3 @cpu(0)>